FROM python:3.11-alpine

# Install dependencies including 'newt' which provides 'whiptail'
RUN apk add --no-cache \
    git \
    curl \
    sudo \
    bash \
    nano \
    newt

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["tail", "-f", "/dev/null"]
